### ISSUE TITLE
New Forked version

### ISSUE THREAD

**Issue by nicola02nb** [LeoKlaus/HeadsetControl-GUI#2]
Hi, I've done some modifications to your program, I think you should check my [fork](https://github.com/nicola02nb/HeadsetControl-GUI)

**Comment by nicola02nb** [comment]
And if you want i can do a PR to merge into your repo, and then you can make me a mantainer

**Comment by LeoKlaus** [comment]
Hey Nicola,

this looks absolutely amazing, great work! I'd be happy to merge your PR :)

**Comment by nicola02nb** [comment]
Created PR #4

**Comment by LeoKlaus** [comment]
I finally got around to it, awesome work! I'll add you as a maintainer for this repo.

**Comment by nicola02nb** [comment]
Good :)
Thanks for giving me the role
